# Generated by Django 3.0.3 on 2020-02-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classyear', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=17)),
                ('foods_drinks', models.CharField(max_length=17)),
                ('classyear', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
